services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes: [".:/app"]
  #   ports: ["8000:8000"]
  #   depends_on:
  #     - db
  #     - redis

  # worker:
  #   build: .
  #   command: celery -A core worker -l info
  #   depends_on: [redis, db]

  # beat:
  #   build: .
  #   command: celery -A core beat -l info
  #   depends_on: [redis, db]